name: CI
on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:

  run:

      runs-on: ubuntu-latest

      matrix:
        
        node-version: '14'

      steps:

        - uses: actions/checkout@v3
        

        - name : Use Node 14 
          working-directory: javascript/  
        - uses: actions/setup-node@v3
          with:
            node-version: '14'
            cache: 'npm'
        
        -name: Rodando ARQUIVO JS
        -run: Node integration.js
       
      