name: CI
on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:

      runs-on: ubuntu-latest

      steps:

        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        

        - name : Use Node 14 
          working-directory: javascript/  
        
          with:
            
            cache: 'npm'
        
        -name: Rodando ARQUIVO JS
         working-directory: javascript/  
         run: Node integration.js
       
      