name: CI-JS
on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
      runs-on: ubuntu-latest

      matrix:
        
        node-version: '14'

      steps:

        - uses: actions/checkout@v3
        - name : Use Node 14      
        - uses: actions/setup-node@v3
          with:
            node-version: '14'
            cache: 'npm'
        
        - run: nom CI-JS
        - run: npm run build --if-present
        - run: npm test 